services:
  reaperalpr:
    image: reaper-alpr
    build: ./reaper/
    command: /reaper/reaper-alpr.py
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data
      - ./reaper:/reaper:ro
      - ./config:/config:ro
    restart: unless-stopped

